### ISSUE TITLE
questions on merged cells styling 

### ISSUE THREAD

**Issue by ChristianYeah** [ShanaMaid/sheetjs#1]
firstly, thank you for open sourcing this great project.

I have one question on merged cell's style,

Supposed I have merged area from A1 to A10

the border style could only be applied to A1, and 2~10 is not defined in the Sheets.SheetN object.

How could I apply border's style to the merged cell in this circumstance.

Thank you

**Comment by ShanaMaid** [comment]
only set style for A1
eg:
ws['A1'].s = {									
  font: {
    name: '宋体',
    sz: 24,
    bold: true,
    color: { rgb: "FFFFAA00" }
  },
};
