### ISSUE TITLE
This package does not have latest updates from SheetJS

### ISSUE THREAD

**Issue by farhankassam2** [ShanaMaid/sheetjs#11]
Hi,

I noticed in the homepage of this NPM package Github repo the following:
**"This branch is 13 commits ahead, 276 commits behind SheetJS/sheetjs:master."**

It seems as though this package is somewhat behind with regards to the updates from SheetJS package which is regularly updated. Can this NPM package be kept up to date with SheetJS changes so that it is more reliable. The idea of having color styles being added to excel exports is a great one that I am currently using for my project, so it would be nice if this package is kept up to date with SheetJS.

Cheers!
Farhan Kassam.

**Comment by ShanaMaid** [comment]
welcome pr！
