### ISSUE TITLE
Undeclared variable QUOTE

### ISSUE THREAD

**Issue by marcoantoniocabrejos** [ShanaMaid/sheetjs#13]
Hi! i'm having a runtime exception with this variable, it throws "QUOTE is not defined". Pleaseo, i need your help. I'm working with esbuild and typescript

**Comment by pavliuc75** [comment]
Same issue (Vue 3 + TS + Vite)

**Comment by IshfaqAhmedProg** [comment]
anybody ever get to solving this issue? had the same issue when using this package with react on one project but not on another where i used next js!

### package.json for the React Project

> {
>   "name": "client",
>   "private": true,
>   "version": "0.0.0",
>   "type": "module",
>   "scripts": {
>     "dev": "vite",
>     "build": "vite build",
>     "preview": "vite preview"
>   },
>   "dependencies": {
>     "@chakra-ui/react": "^2.5.1",
>     "@emotion/react": "^11.10.6",
>     "@emotion/styled": "^11.10.6",
>     "framer-motion": "^10.2.3",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-icons": "^4.8.0",
>     "react-qr-code": "^2.0.11",
>     "react-router-dom": "^6.8.2",
>     "sheetjs-style": "^0.15.8",
>     "socket.io-client": "^4.6.1",
>     "vcards-js": "^2.10.0",
>     "xlsx": "^0.18.5"
>   },
>   "devDependencies": {
>     "@types/react": "^18.0.27",
>     "@types/react-dom": "^18.0.10",
>     "@vitejs/plugin-react": "^3.1.0",
>     "vite": "^4.1.0"
>   }
> }
> 

### package.json for the Next JS Project

> {
>   "name": "scrape-fox",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "lint": "next lint"
>   },
>   "dependencies": {
>     "@fontsource/montserrat": "^4.5.13",
>     "aos": "^3.0.0-beta.6",
>     "axios": "^1.2.2",
>     "eslint": "8.29.0",
>     "eslint-config-next": "^13.1.1",
>     "firebase": "^9.15.0",
>     "next": "13.0.6",
>     "react": "18.2.0",
>     "react-circular-progressbar": "^2.1.0",
>     "react-dom": "18.2.0",
>     "react-firebase-hooks": "^5.1.1",
>     "react-google-recaptcha-v3": "^1.10.1",
>     "react-modal": "^3.16.1",
>     "react-tag-input": "^6.8.1",
>     "sheetjs-style": "^0.15.8",
>     "swr": "^2.0.0",
>     "uuid": "^9.0.0",
>     "validator": "^13.7.0",
>     "xlsx": "https://cdn.sheetjs.com/xlsx-0.19.1/xlsx-0.19.1.tgz"
>   }
> }
