### ISSUE TITLE
设置背景色不工作，无论设置什么颜色，效果都是黑色的

### ISSUE THREAD

**Issue by mcgradycchen** [ShanaMaid/sheetjs#3]
The code is following

 ws[`A${data.length}`].s = {
    fill: {
      bgColor: {
        rgb: 'FFF6C343'
      }
    }
  }
<img width="964" alt="Screen Shot 2021-02-24 at 6 20 20 PM" src="https://user-images.githubusercontent.com/3260884/108986557-3a18a900-76cd-11eb-8068-331b8a6c83cc.png">

**Comment by ShanaMaid** [comment]
fill: {
    fgColor: {
      rgb: 'xxx',
    },
  },
