### ISSUE TITLE
Styles not working

### ISSUE THREAD

**Issue by jjolmo** [ShanaMaid/sheetjs#6]
Styles are not working it seems. Or maybe I'm not using this properly

I import and I'm using the project like this

```import XLSX from 'sheetjs-style'

....
const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet(fullData);

  ws["A1"].s = {
    fill: {
      bgColor: {rgb: 'FF000000'}
    },
    font: {
      name: '宋体',
      sz: 24,
      bold: true,
      color: {rgb: "FFFFAA00"}
    },
  };

```
I tried also with different fonts. I tried without the font block and just see if I could fillt the cell, but the A1 cell is showing unformatted

How we should use this? Seems like it is being totally ignored

Many thanks!

**Comment by yahyaizhar** [comment]
This works for me

use `fill` object like this:
```
fill:{
    patternType:"solid",
    fgColor:{ rgb: "00dce6f1" },
    bgColor:{ rgb: "00dce6f1" } 
}
```

use both `fgColor` and `bgColor` and give them same hex code

**Comment by Bravelemming** [comment]
Same issue -- unable to use the styles:

    let wsSummary: XLSX.WorkSheet = XLSX.utils.json_to_sheet(Summary);
       wsSummary['A1'].s = {	
        font: {
          sz: 24,
          bold: true
          // color: { rgb: "FFFFAA00" }
         },
        };
      XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');
      XLSX.writeFile(wb, fileName + ' ' + new Date().getTime() + EXCEL_EXTENSION);

**Comment by Jesperi02** [comment]
I also can't seem to get even the simplest code to work....
Is there something i'm missing?

    

    // test table
    let table = [ [0, 1, 2], [3, 4, 5], [6, 7, 8] ];

    let fileName = "asd.xlsx"; // file name
    let ws_name = "Raportti"; // sheet name

    let wb = XLSX.utils.book_new(), ws = XLSX.utils.aoa_to_sheet(table); // create a work sheet

    ws["A1"].s = {	// set the style for target cell
        font: {
          bold: true,
        },
    };

    XLSX.utils.book_append_sheet(wb, ws, ws_name); // add worksheet to workbook

    XLSX.writeFile(wb, fileName); // write workbook

    return window.showSaveFilePicker(wb); // show pop up

This works but it doesn't format anything

**Comment by henry-cotton** [comment]
Same here. The workSheet object is being updated before the addition to the workbook, but no styles are applied.

`let workSheet = XLSX.utils.aoa_to_sheet(sheetData);

		sheet.rowsData.forEach((row) => {
			if (!row.consistant && row.failPoint) {
				workSheet[`${row.failPoint}${row.row}`].s = {
					font: {
						color: { rgb: "b50e0e" },
					},
				};
			}
		});
		workBook.Sheets[sheet.name] = workSheet;`

**Comment by RipleWare** [comment]
Got the same problem. No styling applied what-so-ever.
Do I need to include anything, or make reference to the library at all?

Instructions just advise to download the package and apply the styling.

**Comment by mpaustin1993** [comment]
Any updates on this? Styles are still not working.

**Comment by mdi-9** [comment]
Looks like this works only via import. Use webpack.

**Comment by ErnestoTapia22** [comment]
replace:  import * as XLSX from 'xlsx';  to : import * as XLSX from 'sheetjs-style';

**Comment by Jesperi02** [comment]
Instead of messing with webpack, i would use [xlsx-js-style](https://www.npmjs.com/package/xlsx-js-style) that comes with the bundled option and some fixes.

**Comment by ShanaMaid** [comment]
use  
```js
import * as XLSX from 'sheetjs-style';
```

**Comment by ShanaMaid** [comment]
```js
const XLSX = require('sheetjs-style');
const wb = XLSX.utils.book_new();
const ws = XLSX.utils.json_to_sheet([{
  0: 0,
  1: 1,
  2: 2
}], {
  header: ['0', '1', '2'],
});

ws["A1"].s = { // set the style for target cell
  font: {
    name: '宋体',
    sz: 24,
    bold: true,
    color: {
      rgb: "FFFFAA00"
    }
  },
};

XLSX.utils.book_append_sheet(wb, ws, 'sheet1'); // add worksheet to workbook

XLSX.writeFile(wb, 'test.xlsx'); // write workbook
```

**Comment by Babaktrad** [comment]
> This works for me
> 
> use `fill` object like this:
> 
> ```
> fill:{
>     patternType:"solid",
>     fgColor:{ rgb: "00dce6f1" },
>     bgColor:{ rgb: "00dce6f1" } 
> }
> ```
> 
> use both `fgColor` and `bgColor` and give them same hex code

This trick works fine!

**Comment by Michelli28** [comment]
Guys, replace:  const XLSX = require('sheetjs-style'); to const XLSX = require("xlsx-js-style"); !!
