### ISSUE TITLE
Undeclared variable QUOTE

### ISSUE THREAD

**Issue by sfmoreno** [ShanaMaid/sheetjs#7]
Hi, there's an error in the line 21524 of the file xlsx.js. The variable QUOTE is not declared, and this generates an error when you build a project using this library.

`  var APOS = "'"; QUOTE = '"' `

It looks like a typo, I just changed the ; for a , and it works perfectly.

Thanks.

**Comment by ShanaMaid** [comment]
welcome to pr!

**Comment by mephasor** [comment]
Did I miss something or is the typo still there?

**Comment by pascalgn** [comment]
@ShanaMaid I've created a PR for it: #10 🙏

**Comment by JJWins** [comment]
@ShanaMaid Please merge this, I am not able to use this library due to this type error.

Please take a look at the images below
![image](https://user-images.githubusercontent.com/65803455/203528935-9497e96b-1a98-4dc9-a6ed-9e95140d96e1.png)
![image](https://user-images.githubusercontent.com/65803455/203529138-07033467-2ddf-4f63-80a1-6e6f8b37b5e9.png)

**Comment by aldwinp35** [comment]
Use another library

**Comment by WiharlleyWill** [comment]
Use XLSX lib.

`import * as XLSX from 'xlsx';
...

exportToExcel() {
	  const fileName = 'test.xlsx';

		const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(this.arr);
		const wb: XLSX.WorkBook = XLSX.utils.book_new();
		XLSX.utils.book_append_sheet(wb, ws, 'test');

		XLSX.writeFile(wb, fileName);
  }
`

**Comment by SweydManaf** [comment]
has vulnerabilities

**Comment by sagarpatelpro** [comment]
I have a work around.
Just declare "QUOTE" as global variable.

In my case, I am writing a react application, so I just added it to the index.html file.

In index.html file, before including any other source code script.
`<script type="text/javascript"> 
    var QUOTE; 
</script>`

**Comment by ssp7** [comment]
Why is this closed? This is still an issue.
